---
  # Configuring apache2
- name: apache2 configuration file
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
    
- name: create the webpage index.html
  copy: src=index.html dest=/var/www/html/index.html

- name: copy the image resource
  copy: src=Blue_marble.jpg dest=/var/www/html/Blue_marble.jpg
